package com.dev.abhisek30.samachar.core.utils

const val ERROR_INTERNET_CONNECTION = "Please connect to Internet"
const val HTTP_RESPONSE_OK = 200
const val HTTP_RESPONSE_RESOURCE_CREATED = 201


const val HTTP_ERROR_BAD_REQUEST = 400
const val HTTP_ERROR_UNAUTHORIZED_REQUEST = 401
const val HTTP_ERROR_RESOURCE_FORBIDDEN = 403
const val HTTP_ERROR_RESOURCE_NOT_FOUND = 404
const val HTTP_ERROR_RESOURCE_ALREADY_EXIST = 409
const val HTTP_PRE_CONDITION_FAILED = 412
const val HTTP_ERROR_PAYLOAD_TOO_LARGE = 413
const val HTTP_ERROR_UNABLE_TO_PROCESS_REQUEST = 422

const val HTTP_ERROR_INTERNAL_SERVER = 500
const val HTTP_REQUEST_UNSUPPORTED = 501
const val HTTP_ERROR_BAD_GATEWAY = 502
const val HTTP_ERROR_SERVER_MAINTENANCE = 503